export const SHOW_DLT_COMPONENT = 'SHOW_DLT_COMPONENT';
export const HIDE_DLT_COMPONENT = 'HIDE_DLT_COMPONENT';

export const ADD_DLT_FILTER = 'ADD_DLT_FILTER';
export const REMOVE_DLT_FILTER = 'REMOVE_DLT_FILTER';
export const STATE_ON_DLT_FILTER = 'STATE_ON_DLT_FILTER';
export const STATE_OFF_DLT_FILTER = 'STATE_OFF_DLT_FILTER';
export const LOAD_DLT_LOGS = 'ADD_DLT_LOGS';

export const SHOW_MESSAGE_TO_USER = 'SHOW_MESSAGE_TO_USER';
export const SET_DLT_LOGS_AVAILABLE = 'SET_DLT_LOGS_AVAILABLE';
